title: VS Docs
description: Some documentation and ideas
theme: just-the-docs

url: https://vsdocs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
